name: tests

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install dependencies
        run: pip install -r requirements.txt pytest
      - name: run tests
        run: pytest -q
